feat: Реализовать функциональность спринта №13
KokotAlex/java-shareit pull request #1
Opened 2023-01-21 16:30 UTC by KokotAlex

2023-01-21 17:23 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-01-21 17:23 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info("404: {}", exception.getMessage(), exception);
Уровень лога не тот... warn or error

2023-01-21 17:23 UTC, FanaticFiz commented on pom.xml
> +	<version>1.0.1</version>
Хорошей практикой будет указать кодировку
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

2023-01-21 17:23 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ResponseEntity<Object> incorrectParameterException(Throwable exception) {
Кто то тут накопипастил! Название метода явно не соответствует! ))

2023-01-21 17:23 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Соседние классы исключений названы хорошо - в соответствии с HTTP статус кодами которые они будут порождать!
И этот класс стоило бы назвать соответствующе: `BadRequestException`

2023-01-21 17:23 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        List<Item> items = service.getAll(ownerId);
Можно было бы сразу 

```
        return service.getAll(ownerId).stream()
                      .map(ItemMapper::toItemDto)
                      .collect(Collectors.toList());
```

2023-01-21 17:23 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +
Ааааа.... ну это понятная история!

Кот сел на клавиатуру??? )))

2023-01-22 16:59 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info("404: {}", exception.getMessage(), exception);
Исправил

2023-01-22 17:06 UTC, KokotAlex commented on pom.xml
> +	<version>1.0.1</version>
Добавил

2023-01-22 17:13 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ResponseEntity<Object> incorrectParameterException(Throwable exception) {
Исправил))

2023-01-22 17:17 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Исправил

2023-01-22 17:20 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        List<Item> items = service.getAll(ownerId);
Улучшил

2023-01-22 17:23 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +
Исправил))

2023-01-22 17:27 UTC, KokotAlex commented
Большое спасибо за ревью! Ты очень внимателен к деталям, и это круто)

2023-01-22 18:47 UTC, FanaticFiz approved these changes

2023-02-12 12:04 UTC, merged