Add bookings
KokotAlex/java-shareit pull request #2
Opened 2023-02-09 19:22 UTC by KokotAlex

2023-02-10 19:18 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +import lombok.*;
Почему у тебя висит два пул-реквеста?
Каждый раз после прохождения ревью ты должен влить пул-реквест в мастер.

Ты не сделал этого в прошлый раз?

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/resources/application.yaml
> +
Не адекватное кол-во пустых строк это тоже нарушение `code style`

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +//import lombok.*;
Что же это?

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(nullable = false, length = 50)
Где то ты обманываешь!
тут указана длинна поля 50 а в БД она 20 для этого поля!

Будь внимательнее и проверь остальные поля...

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    List<UserDto> getAllDto();
`getAllDto` нет не нужно в названии методов указывать `dto`.
Не нужно привязываться к названиям моделей.

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserDto getDtoById(Long userId) {
Зачем нам два метода getDtoById и getById ?
Точно не нужно двух, всегда можно смапить одно в другое...

2023-02-10 19:18 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> findDtoByText(String text, Long userId);
findDtoByText вот с добавлением этого dti получается по названию метода что метод ищет некую dto! ))

2023-02-12 12:04 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +import lombok.*;
Да, забыл. замерджил предыдущий

2023-02-12 12:05 UTC, KokotAlex commented on src/main/resources/application.yaml
> +
Да, действительно. Удалил лишнее

2023-02-12 12:07 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +//import lombok.*;
Сначала написал класс, а потом понял, что он нигде пока не используется и закомментил чтобы не мешал. Сейчас расскомментил и довел до ума в том виде, который как мне кажется будет дольше использоваться

2023-02-12 12:14 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(nullable = false, length = 50)
Да, не заметил. Спасибо. Проанализировал остальные поля

2023-02-12 12:15 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    List<UserDto> getAllDto();
Переписал систему работы с Dto

2023-02-12 12:15 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public UserDto getDtoById(Long userId) {
Переписал систему работы с Dto

2023-02-12 12:15 UTC, KokotAlex commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> findDtoByText(String text, Long userId);
Переписал систему работы с Dto

2023-02-12 19:15 UTC, FanaticFiz approved these changes

2023-02-13 06:20 UTC, merged